create view vrfq as select a.DOC_NO
,a.PARENT_DOC_NO
,a.PARENT_DOCCATEGORY
,a.PARENT_LINE
,a.USER_DOC
,a.DOC_TYPE
,a.DOC_CATEGORY
,a.DOC_STATUS
,a.PROC_TYPE
,a.ACCTNO
,a.SUBC
,a.CCODE
,a.OURCONTACT
,a.LINES
,a.ULINES
,a.ENTER_DATE
,a.DOC_DATE
,a.DUE_DATE
,a.SHIP_DATE
,a.SHIP_COMPLETE
,a.PRICED_DATE
,a.VALIDTILL_DATE
,a.VALIDFOR
,a.AMENDED
,a.ACKNLDGE
,a.RECV_DATE
,a.PICKED_DATE
,a.SHIPPED_DATE
,a.REVISION
,a.POST_GL_DATE
,a.POST_STK_DATE
,a.APPROVED_DATE
,a.BATCH_NO
,a.BATCH_DATE
,a.PRINTED_DATE
,a.PRINTED_COUNT
,a.CUST_REF1
,a.CUST_REF2
,a.CUST_REF3
,a.CUST_REF4
,a.DROPSHIP
,a.DROPSHIP_ACCT
,a.DROPSHIP_SUBC
,a.DROPSHIP_CCODE
,a.DROPSHIPTO
,a.SHIPTO
,a.SHIPTO_SUBC
,a.SHIPTO_CCODE
,a.BILLTO
,a.BILLTO_SUBC
,a.BILLTO_CCODE
,a.PAYTO
,a.PAYTO_SUBC
,a.PAYTO_CCODE
,a.COMPANYNO
,a.DIVISION
,a.DEPART
,a.HOLD_DATE
,a.HOLD_BY
,a.HOLD_REASON
,a.DELIVERY
,a.TERM_CODE
,a.PRIORITY
,a.SHIPVIA
,a.FOB
,a.FOB_LBL
,a.PACKAGES
,a.SHIPMENT_NO
,a.CONSOL_NO
,a.HOUS_AIRBILL
,a.MAST_AIRBILL
,a.PRINT_PN_MEM1
,a.PRINT_PN_MEM2
,a.PRINT_DOC_MSG
,a.PRINT_DOC_MEM
,a.DOC_INVNO
,a.DOC_INVAMOUNT
,a.GL_ACCOUNT
,a.GL_BYLINE
,a.FORM_1099TYPE
,a.WGHT_TO
,a.VOL_TO
,a.LENGTH_TO
,a.WGHT_TTL
,a.VOL_TTL
,a.LENGTH_TTL
,a.WGHT_GROSS
,a.VOL_GROSS
,a.LENGTH_GROSS
,a.CURENCY_STATE
,a.CURENCY_BASE
,a.CURENCY_CONV
,a.CURENCY_FACTOR
,a.CURENCY_DATE
,a.TAX_SUBTOTAL_TYPE
,a.AEROXCHANGE
,a.SUBTOTAL
,a.SUBTOTALNET
,a.DOC_TOTAL
,a.C_SUBTOTAL
,a.C_SUBTOTALNET
,a.ADDED_DTE
,a.ADDED_USR
,a.AEROXCHANGE_REPAIRS_PROCESS_REQUEST
,a.AGENT_COMMISSION
,a.ALT1
,a.ALT2
,a.BLINE
,a.BLINEYN
,a.CANCELED
,a.CATEGORY
,a.CHARGE_AMOUNT
,a.CLOSE_QBACK
,a.COND
,a.CONTRACT_DOC_NO
,a.CONV_DOC
,a.CONV_DOC_CATEGORY
,a.CONV_LN
,a.COST
,a.COST1
,a.COST1_UM
,a.COST2
,a.COST2_UM
,a.COST3
,a.COST3_UM
,a.COST_CAP
,a.COST_CURENCY
,a.COST_DATE
,a.COST_DOC
,a.COST_DOCLINE
,a.COST_DOC_CATEGORY
,a.COST_FACTOR
,a.COST_UM
,a.CUSTOM_PRICE
,a.CUSTOM_PRICE_UM
,a.CUST_PN
,a.CUTTING_DIRECTION
,a.CUTTING_REQUIRED
,a.C_AGENT_COMMISSION
,a.C_CHARGE_AMOUNT
,a.C_COST
,a.C_COST_CAP
,a.C_CURENCY
,a.C_CUSTOM_PRICE
,a.C_DATE
,a.C_DOC_TOTAL
,a.C_EXCLUDE_PART_COST
,a.C_FACTOR
,a.C_PRICE_PER_PIECE
,a.C_PRICE_PER_WEIGHTUM
,a.C_SOURCE_PRICE_VALUE
,a.C_TARGETPRICE
,a.C_UNITP
,a.C_UNITP1
,a.C_UNITP2
,a.C_UNITP3
,a.DESCRIPTN
,a.DISCOUNT
,a.DISCOUNT_TYPE
,a.DLV
,a.EXCLUDE_PART_COST
,a.EXCLUDE_PART_COST_REASON
,a.EXCLUSIONS
,a.FACTOR
,a.HPOST
,a.IMPORT_EXPORT_LICENSE
,a.IMPORT_EXPORT_OVERRIDE
,a.IMPORT_EXPORT_REQUIRED
,a.LAST_PRICE_APPROVED
,a.LENGTH_FROM
,a.LENGTH_FROM_TTL
,a.LENGTH_TO_TTL
,a.LINE
,a.LINE_REF
,a.LINE_TYPE
,a.LOGNO
,a.LSTATUS
,a.MAX_SELL
,a.MFG
,a.MFG_SUBC
,a.MIN_QTY
,a.MIN_SELL
,a.NOCHARGE
,a.NOTE
,a.NO_CHARGE
,a.PARTNUMBER
,a.PARTSERIAL
,a.PART_SSN
,a.PICKED_BY
,a.PICKED_ON
,a.PICK_LOCATION
,a.PICK_STATUS
,a.PIECE_LENGTH
,a.PIECE_WIDTH
,a.PN_RCV_AS
,a.PN_RCV_AS_SUBP
,a.PN_RCV_LOGNO
,a.PRICE_APPROVAL_DATE
,a.PRICE_APPROVED_BY
,a.PRICE_BY_WEIGHT
,a.PRICE_CONTRACT_DOC_NO
,a.PRICE_CONTRACT_TYPE
,a.PRICE_PER_PIECE
,a.PRICE_PER_WEIGHTUM
,a.PRINTED
,a.PRINTLINE
,a.PRN_PN_MEMO1
,a.PRN_PN_MEMO2
,a.QBACK
,a.QORDER
,a.QREQ
,a.QSCHEDULE
,a.QSHIP
,a.QTY_CHANGE
,a.QTY_CHANGE_UM
,a.QTY_CONVERT
,a.QTY_FACTOR
,a.QTY_INSTOCKREV
,a.QTY_UM
,a.RECEIVED_BY
,a.RECEIVED_ON
,a.RECLOCK
,a.REF1
,a.REF2
,a.REF3
,a.RELEASED_BY
,a.RELEASED_ON
,a.REPLENISHMENT_COST
,a.REQUESTED_PARTNUMBER
,a.REQUESTED_PN_SUBP
,a.RESERVED_BY
,a.RESERVED_ON
,a.RNG
,a.ROHS_COMPLIANCE
,a.SERIAL_NO
,a.SOURCE_PRICE
,a.SOURCE_PRICE_VALUE
,a.STATUS
,a.SUBP
,a.TARGETPRICE
,a.TOTAL_WEIGHT
,a.ULINE1
,a.ULINE2
,a.UNDER_WARRANTY
,a.UNITP
,a.UNITP1
,a.UNITP1_UM
,a.UNITP2
,a.UNITP2_UM
,a.UNITP3
,a.UNITP3_UM
,a.UNITP_UM
,a.UPDATED_DTE
,a.UPDATED_USR
,a.VOL_FROM
,a.VOL_FROM_TTL
,a.VOL_TO_TTL
,a.WEIGHT_PER_PIECE
,a.WGHT_FROM
,a.WGHT_FROM_TTL
,a.WGHT_TO_TTL
,a.ADR1
,a.ADR2
,a.ADR3
,a.CITY
,a.COUNTRY
,a.COUNTY
,a.FAX1
,a.FAX2
,a.INTERNET
,a.INVOICE_TYPE
,a.ISACTIVE
,a.NAME
,a.PAD
,a.PAID_BY_ACH
,a.PAID_BY_WIRE
,a.REGION
,a.REGISTRATION_NO
,a.REGISTRATION_UPD
,a.REGISTRATION_VALID
,a.SHIP_CODE
,a.SHIP_NO
,a.SHIP_TYPE
,a.SITA
,a.SPC_2000_C
,a.SPEC2000
,a.STATE
,a.TEL1
,a.TEL1_EXT
,a.TEL2
,a.TEL2_EXT
,a.TEL_PFIX
,a.WEB_SITE
,a.ZIP
from rfq a where lower(name) in ('duncan aviation','precision accessories & instruments',
'p&wc leasing',
'mint turbines llc',
'western aircraft inc.',
'flexjet, llc',
'jssi parts llc',
'eurotec vertical flight solutions',
'summit aviation inc',
'africair, inc.',
'vertex aerospace llc',
'kci aviation',
'netjets aviation, inc.',
'sierra nevada corporation',
'air methods corporation',
'flexjet, llc',
'era helicopters llc',
'west star aviation',
'aeropec international corp',
'sikorsky aircraft corporation',
'sterling helicopter',
'avex inc',
'life flight network, llc',
'aviation instrument services',
'west star aviation, inc.',
'banyan air service inc',
'helinet aviation services llc',
'jalux americas inc',
'med-trans',
'wesco manufacturing',
'av industries',
'era helicopters llc',
'bristow us llc',
'horizon air industries, inc.',
'metro aviation, inc.',
'fbi academy',
'embraer solutions llc',
'empire airlines',
'satair usa, inc',
'west star aviation',
'southeast turbines corp.',
'seneca flight operations',
'jaguar aviation industries corp.',
'consolidated turbine specialists',
'jet access aviation',
'phi inc.',
'reach air medical services',
'skytech inc.',
'md helicopters, inc.',
'planesmart aviation',
'zenith aviation inc',
'aero star aviation l.l.c.',
'southern cross aviation',
'talon air llc',
'magellan aircraft services lllp.',
'atlantic coast aircraft services',
'dyncorp international',
'win aviation inc.',
'l-3 technologies.',
'andrew industrial inc',
'chevron u.s.a. inc.',
'general atomics aeronautical',
'mather aviation llc',
'corvus airlines',
'talon air llc',
'rsg aviation, inc.',
'image air charter, llc',
'helicopter maintenance',
'maryland state police aviation',
'special services corp',
'j & s plating and repair',
'advanced helicopter services',
'precision air',
'stella air',
'mag aerospace',
'pacific turbine usa,llc',
'heliflite shares llc',
'turbine traders ltd.',
'boeing distribution services inc',
'dynamic aviation group, inc.',
'rotorcraft support, inc.',
'phi inc.',
'basler turbo conversions, llc',
'mint turbines llc',
'aero air llc',
'west air inc.',
'quest diagnostics clinical',
'careflite',
'high performance aircraft inc',
'des moines flying service',
'straight flight inc',
'university air center',
'tmt research development',
'mecaer aviation group inc',
'goodrich/delavan carroll operation',
'fjet management',
'aero8, inc.',
'jc airparts',
'pj helicopters inc.',
'cascade helicopter services',
'aero-flite inc.',
'apollo medflight llc',
'bridger aerospace',
'bristow us llc',
'ethosenergy accessories&components',
'japan airlines co., ltd.',
'horizon air inc.',
'b i aero, llc',
'euravia north america',
'ohlinger industries inc.',
'calco aerospace',
'skyways ltd',
'proponent',
'rich products corporation',
'united airlines',
'ab jets',
'universal turbine parts inc',
'mattis aerospace',
'epic aircraft llc',
'phi air medical, llc',
'peniel group llc',
'life link iii',
'tallamond llc',
'northland aviation services inc',
'malibu aerospace',
'mead aircraft services kansas city',
'massachusetts mutual',
'mather aviation llc',
'leki aviation usa inc',
'piedmont airlines',
'pro star aviation llc',
'aerotechnic usa, inc.',
'alaska central express',
'mercy flight inc.',
'aira aviation',
'epps aviation',
'united aerospace corp',
'duncan aviation inc.',
'netjets sales inc.',
'mountain air cargo',
'duncan aviation inc',
'unical aviation inc',
'yingling aviation',
'eagle creek aviation services',
'cutter aviation',
'aci jet',
'martin aviation lp',
'muncie aviation company',
'jet tech ltd',
'atlas aircraft center',
'bel-bac international, inc.',
'skytech inc.',
'mid-continent aviation services inc',
'cutter aviation dallas, inc.',
'four points aero services',
'm3 technology',
'alaska air transit',
'fly exclusive',
'travis county star flight',
'southern airways express',
'stevens aerospace and defense',
'sol aviation',
'phi inc.',
'kell-strom tool company inc',
'bristow us llc',
'jet aviation flight services, inc.',
'weatherstone air inc.',
'pegasus technologies inc',
'raytheon technologies',
'government of israel',
'consolidated aircraft supply c',
'ibm flight operations',
'turbopower, llc.',
'united turbine',
'l-3 vertex aerospace llc',
'cardinal health',
'hartzell propeller inc',
'stevens aerospace',
'spectrum health hospitals',
'jet support services inc (jssi)',
'emerson electric co.',
'central flying service, inc.',
'frost flying inc.',
'vertex aerospace',
'sierra pacific industries',
'flightcraft inc',
'pfizer inc.',
'associated aircraft group',
'metro aviation, inc.',
'corvus airlines',
'sc johnson & son inc.',
'gama aviation llc',
'elliott aviation',
'airforce turbine service',
'signature technicair',
'ge corporate air transport',
'signature technicair',
'blackhawk modifications, inc.',
'turbines, inc',
'papillon grand canyon',
'lincoln financial group',
'deer horn aviation',
'r&l carriers',
'taca international airlines s.a.',
'sp aviation, inc',
'salt river project',
'advantage aircraft services',
'kansas city aviation center',
'executive jet management',
'smithfield foods inc.',
'rice lake air center',
'heritage turbines inc.',
'saywell international, inc.',
'encompass health corporation',
'niacc technology inc',
'travelers indemnity co.',
'premier jet center',
'federal aviation administration',
'mid america jet',
'global airtech',
'american general supplies inc.',
'gray & company inc',
'global aviation inc',
'aviation welding technologies',
'lone mountain aviation inc',
'dyncorp international llc',
'thornton aircraft company',
'malibu aerospace',
'fargo jet center, inc.',
'alpha enterprises, inc',
'lane aviation, inc',
'bering air inc',
'best aviation inc.',
'colson & colson general contractors',
'commerce bancshares inc.',
'component repair technology',
'stat medevac',
'summit helicopters, inc.',
'temsco helicopters inc.',
'windway capital corporation',
'city of los angeles',
'kaa corporation',
'aerovision international',
'honeywell international',
'alpine aviation',
'arrow aviation co llc',
'aviation spares and svcs intl',
'eaglemed llc',
'baron aviation services, inc.',
'cutter aviation',
'engine management specialist llc',
'flightline group',
'gh enterprises, inc',
'helicopter services of utah inc',
'heli mart inc',
'home depot flight dept',
'maclean-fogg company',
'north star aviation',
'reliant aircraft services',
'rop aviation, inc',
'rossi aircraft inc',
'south florida jet center inc.',
'stevens aerospace',
'stevens aerospace and defense',
'sun aviation inc.',
'west coast charter',
'wright air service',
'midwest turbine services',
'tulsair beechcraft inc.',
'winner aviation',
'patrick v. gough co. inc.',
'shoreline aviation inc.',
'lane aviation',
'green bay packing inc',
'management west llc',
'uniflight, llc',
'black diamond aviation group llc',
'bauer aviation llc',
'triangle aviation solutions',
'chevron texaco aircraft operations',
'tradewind aviation, llc',
'southwest airmotive corp',
'vulcan flight management',
'global turbine parts corp',
'north memorial medical center',
'leco corporation',
'western pilot service, inc.',
'delaware park',
'flying colours corp',
'phoenix police air support unit',
'friend aircare',
'airtec inc',
'ultimate jetcharters, llc',
'mercy st. vincent medical center',
'clay lacy aviation',
'maine aviation',
'cin-air management, llc',
'morrison aircraft inc.',
'worthington aviation parts, inc.',
'southern air systems, inc.',
'national grid service company',
'engine & airframe solutions',
'devon realty advisors llc',
'flir systems inc.',
'engine overhaul services',
'ikhana group inc',
'berry aviation inc',
'jbi helicopter services',
'engine & airframe solutions',
'l.j. associates d/b/a l.j. aviation',
'heloair, inc',
'fatair inc.',
'security aviation',
'life time fitness, inc.',
'mangon aircraft, inc',
'sl management llc',
'richmond american flight operations',
'duke energy corporation',
'faa',
'mente llc',
'constant aviation',
'southern california edison',
'defense technology equipment',
'spokane turbine center',
'at&t services',
'b i aero, llc',
'metro aviation-bdn',
'mission aviation fellowship',
'olympic aviation',
'aviatrix, inc.',
'haggan aviation',
'kamaka air inc',
'ontic engineering',
'high flight meridian llc',
'jetsuite headquarters',
'mecanex usa inc',
'mach one air charters inc',
'regional one, inc.',
'basler turbo conversions llc',
'airmed lnternational bhm',
'pollard aircraft sales, inc',
'air centre, llc',
'davinci jets llc',
'sierra nevada corporation (gvo)',
'neal aircraft',
'aog jet support inc',
'avmax montana inc.',
'cosgrove aircraft service, inc',
'promega corporation',
'bombardier flexjet',
's3 international, llc',
'boca aircraft maintenance, llc',
'triumph accessory services',
'seven bar aviation llc',
'ies group',
'sevenbar aviation, llc.',
'davis aviation inc.',
'phenom aviation, llc',
'attop international llc',
'avianca inc',
'flight management corporation',
'defense support services llc',
'arizona department of public safety',
'flatrock associates ii llc',
'propel aviation sales & service llc',
'west coast aircraft maintenance',
'valair aviation',
'sky mart sales corp',
'midwest medical transport co',
'prime turbines',
'iomax aircraft',
'intercontinental jet service',
'key lime air, corp.',
'state of south dakota',
'rgb enterprises llc',
'mokulele flight service',
'mather aviation',
'apex aviation',
'phi inc.',
'ascension air management, inc.',
'jet linx aviation, llc',
'rbr maintenance inc',
'brim equipment leasing inc',
'arapahoe aero inc',
'aramco services company',
'bristow us llc',
'standard process inc',
'pacific coast jet llc',
'turner sales, llc',
'scott richard aviation services',
'sierra nevada corporation',
'accel aviation accessories',
'dixie jet & rotor service llc',
'sheetz aviation',
'windway capital corp',
'richmor aviation inc',
'meyer tool inc',
'intermountain life flight',
'jet east ttn',
'm7 aerospace',
'premier aircraft service',
'aero experts',
'solairus aviation',
'south air helicopters inc.',
'thalassa air corporation',
'the duchossois group',
'altius aviation, llc',
'group vi',
'midwest malibu center',
'jgils, llc',
'socal jet services, inc',
'jps aero, llc',
'l3 communications integrated',
'j. new aviation llc',
'stanley black & decker aviation',
'sureal vision, ltd',
'infinity aviation services',
'coastal mechanics co., inc.',
'agsur aviones',
'virgin galactic',
'aero investment group',
'san francisco helicopters llc',
'the champion company',
'des moines flying service',
'exelon business services co. llc',
'northern air maintenance service',
'northern wings repair, inc',
'thumb energy inc.',
'helicopter flight services',
'stephens investments holdings llc',
'omni air transport  llc',
'aero flite inc',
'martinaire aviation llc',
'wheels up',
'vaerus aviation, inc.',
'uniflight westpenn',
'avionics & maintenance west, inc.',
'lamar aero',
'cambridge flight support, llc',
'kcac aviation',
'signature technicair',
'aircraft parts store llc',
'challenger management llc',
'naples jet center',
'aircraft support & services, inc.',
'pathfinder aviation inc',
'aitheras aviation group',
'dumont aviation',
'halo flight inc',
'427mj llc',
'nicholas services llc',
'delta rim, inc',
'rbc turbine components llc',
'airdogs supplies inc',
'broadwing aviation',
'federal aviation administration',
'townsquare radio, llc',
'transworld aviation usa, llc',
'mw aircraft services',
'davenport aviation inc.',
'la porte aviation services',
'mercury trading company',
'tropic ocean airways',
'n1 engines, llc',
'tumbleweed aero service llc',
'us forest service',
'mesquite aircraft sales & service',
'lubbock aero',
'owl aerospace',
'tex-air parts international, ltd.',
'topcast aviation supplies co ltd',
'aero assets llc',
'aero contractors ltd',
'avia source, inc.',
'klx inc',
'falcon crest aviation supply, inc.',
'goodrich corp. fss',
'goodrich turbine fuel tech',
'iso group, inc.',
'mem corporation',
'northern wings repair, inc.',
'northrop grumman aviation division',
'relli technology, inc.',
'simtech, inc.',
'sit corporation',
'tennessee valley authority',
'vonsvon pacific solutions, inc.',
'arista aviation services',
'mw aircraft services inc',
'bba aviation usa ap',
'newcastle aviation',
'turbine conversions ltd',
'allied defense industries, inc',
'execujet charter service inc',
'r.a.m.s. aviation company, inc.',
's&k logistics services',
'yingling aviation',
'white lodging',
'aoa management company',
'hampton airways',
'unical defense inc.',
'boutique air',
'exclusive jets llc',
'donald mcnamara',
'airline spares america, inc. (asa)',
'two bear air rescue',
'pierce aviation',
'liberty media corporation',
'cns aviation inc',
'air parts international sales',
'ftb international corp',
'skytech aviation',
'pinair tech corp',
'maritime helicopters',
'solairus aviation',
'red river aircraft leasing llc',
'constant aviation',
'miami technics llc',
'kinetica deepwater express llc',
'adex aerospace, inc.',
'akima logistics services',
'lifeflight of maine',
'cmh homes, inc.',
'kinetica deepwater express llc',
'caesars entertainment',
'phoenix composite solutions',
'kit turbines, llc',
'sikorsky aircraft company',
'north air care',
'mro support inc',
'executive airshare llc',
'burnett aviation co. inc.',
'go aviation',
'central aviation solutions',
'ametek drake air',
'mil-com industrial sales inc',
'erickson incorporated',
'aaddesk systems ltd',
'ams industries',
'maine aviation corp.',
'palm beach county sheriffs office',
'turbine aero repair',
'integrated procurement technologies',
'wingman aircraft repair, inc',
'blackwell consulting, inc',
'dhl network operations',
'ipd aerospace',
'l3 technologies, inc',
'jetsplus inc',
'live oak bank',
'dycom industries, inc',
'asap semiconductor',
'barfield precision electronics',
'star aviation services',
'mem corporation',
'bizav support llc',
'constant aviation',
'berwind corporation',
'hawthorne global aviation services',
'northland aviation',
'green bay packaging aviation',
'sweethelicopters',
'leidos innovations',
'klh partners',
'jabil inc.',
'k-r aircraft inc',
'chad crank',
'seattle aviation solutions',
'pae aviation andtechnical',
'jetright',
'constant aviation',
'mag aerospace',
'southern airways express',
'james aeronautics',
'aba air group',
'integra aviation llc',
'mc ride llc',
'wilbur ellis air llc',
'wings investment, llc',
'dij properties management, llc',
'med-trans corporation',
'guardian flight, llc',
'donald farms inc',
'clay lacy',
'chronos aviation',
'aero-glen international llc',
'2 wings aircraft parts llc',
'planet nine private air llc',
'perna leasing, inc',
'upmc - university of pittsburgh',
'aircraft parts store llc',
'sky partners inc',
'masco service corp.',
'hillsboro global aviation, inc',
'electreq llc',
'david awrey randall revocable trust',
'jetsuite',
'hs aero group',
'burhani enterprises, inc.',
'man diesel and turbo north america',
'burwell enterprises',
'echostar operating llc',
'tri-state heli group',
'heli-mart, inc.',
'armin technology llc',
'coastal aircraft maintenance',
'true north aviaiton, llc',
'airframe & powerplant solutions llc',
'auto advisors group llc',
'la aerospace, inc.',
'area 51 esg, inc',
'jlc charters, llc',
'fieldtech avionics & instruments',
'mtc aviation llc',
'air bear aviation inc',
'boeing distribution services inc.',
'aeromaster sa llc',
'cme arma, inc',
'a-tec aircraft maintenance center',
'wightman financial network llc',
'man energy solutions usa',
'ot trans, inc',
'calvert aviation llc',
'sr aerospace, llc',
'jet 60 llc',
'track up technical corp',
'fackler aviation services llc',
'vcap aviation',
'pascal development llc',
'managed healthcare services (mhs)',
'marina district development llc',
'pac aviation international,inc',
'3 gals industrial, llc',
'southwest florida aviation',
'aeronautic investments inc',
'amsan group inc.',
'ravn',
'pilot corporation',
'vomke, llc',
'kinetic aviation maintenance',
'banner aircraft international, inc.',
'maney aircraft inc',
'ruag inc',
's3 aerodefense, llc',
'1906 llc',
'argo turboserve corporation',
'envoy air inc',
'piedmont airlines inc.',
'hawaiian airlines',
'hawaiian airlines',
'aar international inc',
'federal express',
'delta airlines inc',
'galaxy aviation corp',
'turbine technologies corp.',
'jetblue airways',
'aero accessories and repair inc',
'diversified aero services, inc',
'aog aviation services',
'rose aerospace, llc',
'republic airways holding inc.',
'pegasus elite aviation inc',
'sts component solutions, llc',
'commutair',
'global parts.aero',
'united airlines - hqjap',
'kingfisher air services',
'haeco',
'safe fuel systems',
'embraer aircraft maintenance',
'alaska seaplanes',
'freedom aviation, inc.',
'wiggins airways',
'illuminair support corp',
'yuba-sutter aviation',
'western aircraft',
'des moines flying service',
'aero twin, inc.',
'professional pilots aircraft',
'kapowsin air sports ltd.',
'redding aero enterprises inc.',
'kansas city aviation center inc',
'sas institute inc.',
'elliott aviation inc.',
'meridian air group',
'reliable jet maintenance, llc',
'west coast turbines',
'constant aviation, llc',
'indy jet management',
'american jet management',
'delta private jets',
'flightsafety international cessna',
'avion capital corporation',
'celerak inc.',
'corporate air',
'jet-care international',
'tnt aviation,llc',
'claire air, llc',
'vpj holdings llc',
'gama aviation llc',
'pen turbo aviation inc',
'atech turbine components inc.',
'prime turbines inc',
'tyson foods, inc.',
'timken alcor aerospace',
'planesense, inc.',
'preferred airparts',
'hamilton sundstrand',
'corporate air',
'ameriflight llc',
'aramco services co',
'asiana airlines',
'air india ltd.',
'commutair',
'corning inc (aviation dept)',
'sikorsky aircraft corporation',
'embassy of greece',
'embassy of the republic of turkey',
'skytech inc.',
'piedmont airlines inc.',
'souther field aviation',
'bombardier business aviation',
'colombian air force',
'u.s. epperson',
'turbine weld inc.',
'l-3 communication',
'mb aerospace warren, llc',
'duncan aviation inc.',
'great lakes aviation',
'trans states airlines',
'parker drilling co.',
'mitsui bussan aerospace corp.',
'continental express m/s gtw/ce',
'tempus aircraft sales & service',
'japan airlines co., ltd.',
'korean air lines',
'county of los angeles fire dept.',
'ansett aircraft spares & service',
'the new avex, inc.',
'island air',
'cascade airframe repair inc.',
'skywest airlines',
'nascar, inc',
'airforce turbine service, ltd',
'image air',
'caad inc',
'mid-continent aircraft corp',
'tiffin aire inc.',
'federal aviation administration',
'socata aircraft',
'papillon grand canyon',
'bombardier services corporation',
'csa air, inc',
'epps aviation',
'airplane company of salinas inc',
'edwards rotorcraft solutions inc.',
'greenpoint aerospace',
'hawker beechcraft services',
'precision electronics',
'bombardier inc.',
'hawker beechcraft - pre petition',
'suburban air freight inc',
'avianca inc, as agent for',
'rogers helicopters inc',
'american international group',
'columbia air services inc',
'southeast turbines corporation',
'corp flight mgmt',
'air center helicopters inc',
'causey aviation services inc',
'werner aero services',
'aire corr, llc',
'duncan aviation',
'crownair aviation',
'mather aviation',
'amway aviation department',
'air repair inc.',
'air eagle llc',
'gg aircraft, llc',
'elliott aviation aircraft',
'ross rectrix mro, llc',
'american aviation inc.',
'city of los angeles',
'ross aviation flight maintenance',
'pen air (the spirit of alaska)',
'dole purchasing co.',
'aviotrade inc',
'j & m aircraft co.',
'healthsouth aviation, inc',
'bombardier aviation services',
'eb flight department',
'nte aviation ltd',
'jeld-wen aviation',
'starport',
'shearer aviation',
'tulsair beechcraft inc.',
'aero ways inc.',
'heliponents inc',
'interaero inc',
'reading jet maintenance',
'new york city police department',
'avjet corporation',
'learjet inc.',
'l & m aircraft',
'american express company',
'purdue university',
'federal aviation administration',
'red river montana, llc',
'rite aid corporation',
'hansair logistics inc.',
'jet aviation',
'kimball international transit',
'rcr air inc.',
'china airlines cargo',
'keystone aviation llc',
'goodyear flight operation',
'h&l accessory inc',
'wisconsin aviation  4 lakes inc.',
'pacific american corporation',
'triumph air repair',
'aircraft maintenance',
'miami-dade county',
'tristate careflight',
'bloomberg services',
'triumph engines - tempe',
'norcross air inc.',
'turboanalisis inc',
'aero precision industries, inc.',
'construction helicopters, inc.',
'southeastern aircraft',
'global aviation resources inc.',
'wencor',
'honeywell international',
'aramco associated company',
'turbo air inc.',
'tristate careflight',
'sun aviation inc.',
'burlington air center',
'stevens aviation',
'chicago fire department',
'classic services ii, llc',
'aero parts ltd.',
'sky trek aviation',
'hale aircraft inc.',
'aero turbine components inc',
'cessna citation service center',
'elliott aviation of minneapolis',
'coast aviation support',
'dean aircraft service inc',
'international aviation support',
'bombardier aircraft services',
'marshalltown aviation inc',
'dean aircraft services inc.',
'central arkansas turbines inc.',
'aircraft associates inc.',
'basin electric power cooperative',
'hm aviation inc.',
'archer daniels midland company',
'sr aviation inc',
'pac west helicopters',
'epic air, llc.',
'roberts aircraft co.',
'infinity air, inc.',
'citgo petroleum corporation',
'midwest turbines llc',
'dean aircraft service',
'everts air cargo',
'tulip city air service inc.',
'willis lease finance corporation',
'neptune aviation services, inc',
'palm beach aircraft services inc',
'white mountains capital inc.',
'graylyn turbines inc.',
'hov-aire, inc',
'aviation consultants inc',
'air products and chemicals inc.',
'alpine aviation inc.',
'aero charter inc.',
'agri flite service inc.',
'badger liquor company inc.',
'central american airways',
'chandler aviation',
'columbia helicopters inc.',
'dale aviation inc.',
'dodson international parts, inc',
'granite construction inc.',
'growmark inc.',
'helicopters inc.',
'luck stone corporation',
'nebraska public power district',
'northeastern aviation corp',
'red wing shoe company',
'royal aviation llc',
'ryan air inc.',
'skyway ltd.',
'south dakota dept of transportation',
'ohio department of transportation',
'taughannock aviation',
'thornton corporation',
'united airlines inc.',
'tenax aerospace',
'embassy of the h.k. of jordan',
'emery air inc',
'hubbard broadcasting inc',
'pacific simon llc',
'kci aviation',
'avcraft technical services',
'sikorsky commercial, inc.',
'air parts intl sales',
'aircraft service company ltd',
'airplane company',
'conocophillips company',
'aviation laboratories',
'bai, inc.',
'bering strait school district',
'big island air',
'bunn-o-matic corporation',
'castle aviation, inc.',
'centurytel service group llc',
'corporate air technology',
'ct aerospace, lp',
'cosgrove aircraft',
'davis air repair',
'dole fresh fruit',
'dominion aviation services inc',
'elliott aviation',
'executive airshare llc',
'executive fliteways, inc',
'gary jet center',
'dyncorp international, llc',
'gulf atlantic airways dba',
'hamilton sundstrand',
'high performance aircraft',
'jet aviation business jets',
'constant aviation',
'jetset airmotive co inc',
'j r simplot company',
'kubecka flying service',
'martin marietta materials inc.',
'mayo aviation, inc.',
'menard inc.',
'midstate aviation inc.',
'keystone aviation llc',
'million air - houston',
'minuteman av corp',
'monarch air',
'murphy oil corporation',
'north texas aircraft svc inc.',
'pentastar aviation llc',
'ppl aviation, llc',
'presidential aviation inc',
'richardson aviation',
'salt river project flight',
'san bernardino sheriff dept',
'scottsdale hangar one',
'signature flight support',
'sky way enterprises, inc.',
'l j aviation',
'standridge color corporation',
'thornton aircraft company',
'trinity river authority of texas',
'tps aviation inc',
'heritage aviation',
'west tennessee aviation',
'western airways, llc',
'yingling aircraft',
'tulsair beechcraft/memphis, inc.',
'baron aviation services, inc.',
'lubbock aero',
'turboprop east inc',
'pacific connection',
'interstate turbine management',
'flight works inc.',
'elliot aviation of minneapolis',
'turbine standard ltd.',
'turbo air, inc.',
'edwards jet center',
'meridian air charter',
'east texas h.s.i.',
'defense support services llc',
'turbine aircraft services',
'cc services inc',
'executive aviation, inc.',
'a-ok jets inc.',
'sky river management',
'the chickasaw nation',
'champion air, llc',
'mewbourne oil co',
'coca cola consolidated, inc',
'florida jet center inc',
'priester aviation llc',
'masco flight operations',
'flightworks, inc.',
'precision jet',
'new york police department',
'cc industries',
'jack henry & associates, inc',
'jet linx aviation, llc',
'queen bee air specialties inc.',
'eagle aviation inc',
'embassy of the republic of korea',
'sterling aviation',
'j & s plating and repair',
'iptn north america inc',
'aerostar aircraft corporation',
'yulista support services llc',
'signature technicair',
't k aviation inc',
'allstate insurance company',
'sea & air sales',
'flight solutions, inc.',
'aspen helicopters inc.',
'precision heliparts inc.',
'bell aviation',
'malone air charter inc.',
'jetselect llc',
'cimarex energy co.',
'elite turbine maintenance',
'concord jet service inc.',
'wesco manufacturing',
'citation technology partners',
'spirit airlines inc',
'lancair international inc.',
'hillsboro aviation inc',
'global pacific aviation inc.',
'north memorial air care',
'jet air systems',
'csa air inc.',
'falcon express aviation',
'medical air inc',
'aramco associated company',
'sanmina - sci corporation',
'hoar construction, llc',
'a & s international supply',
'delta airelite business jets',
'charter air transport inc.',
'lloyd usa inc',
'the maintenance group',
'flightsafety international inc.',
'hunt aviation services, llc',
'm.a.r. fun llc',
'regional one, inc.',
'mobile crane services inc.',
'noble jet',
'jetspares international, inc.',
'big island air',
'via airlines',
'kellstrom materials',
'ab aviation llc',
'jal aeroparts (usa) corp.',
'c & s wholesale grocers',
'abilene aero incorporated',
'starr equipment corp.',
'miami jet professionals',
'ag air maintenance services, inc',
'aviation partners of america',
'm7 aerospace',
'darby holdings ii llc',
'mclane company, inc',
'united parcel service company',
'jet international company l.l.c',
'eve ii, llc',
'jalux americas inc',
'eclipse aviation (jet complete)',
'two brothers aviatin',
'anderson & anderson',
'reeder flying service, inc.',
'meridian jet center',
'era helicopters llc',
'air wilmington inc',
'kti inc.',
'hawker beechcraft services',
'million air dallas',
'w.w. grainger inc.',
'cigna',
'national american university',
'ok3 air',
'ludwig & associates',
'talon air',
'rbc turbine components llc',
'phillips aviation company',
'bombardier learjet',
'first energy service company',
'h & o aviation, llc',
'don davis aviation',
'sterling helicopter',
'jet tech ltd',
'greenpoint aerospace',
'norcatec llc',
'spectra jet, inc',
'kiernan companies',
'avmats',
'aeronautic investments, inc.',
'army fleet support',
'la county fire dept',
'paradigm aerospace corporation',
'grady-white boats, inc.',
'jal aeroparts (usa) corp',
'bode aviation inc',
'elliott aviation flight services',
'travel management co ltd',
'capital logistic services',
'growers air inc.',
'n384jw, llc',
'nustar aviation llc',
'prime air llc',
'n888ce flight management',
'aircraft mechanical services, inc.',
'engine management specialist llc',
'telford aviation inc.',
'calstar air',
'advancetech aircraft maintenance',
'wild horses aviation, llc',
'santa fe aero services',
'glendale police air support',
'arlington aircraft of nevada',
'jet aviation st.louis,inc',
'joe vaughn spraying inc.',
'tc offshore llc',
'prior aviation service inc',
'becton dickinson & co.',
'kingfisher air services',
'mitchell aircraft spares, inc',
'quest aviation inc',
'aviation turbines international',
'management services inc',
'goshen air center',
'et mechanical',
'el paso, inc',
'interlaken capital aviation',
'shadowfax communications, inc.',
'executive aircraft maintenance',
'million air - richmond',
'dallas aviation, inc.',
'med - air inc',
'bismarck aero center',
'eclipse transport llc',
'proav aviation management, inc.',
'koch aviation-atlanta',
'usaa',
'cpx charter li',
'aerolynx air charter',
'wichita air services inc.',
'falcon commercial aviation',
'acm aviation inc',
'universal technologies corp',
'ametek thermal systems',
'h&l accessory',
'worldwide jet charter,inc',
'talon air, inc.',
'maverick airlines inc',
'maven engineering corporation',
'advanced air llc',
'calstar',
'tri star aviation company',
'precision turbines, inc',
'federal defense industries',
'lexicon, inc.',
'orange county fire authority',
'polaris aviation solutions llc',
'tti aviation llc',
'waltzing matilda aviation llc',
'garmin international',
'reach',
'airspeed aviation, llc',
'camm air',
'aerotec services',
'steelcase aviation',
'dreamline aviation llc',
'valkyrie 7x llc',
'anr pipeline company',
'north rock aviation',
'seaport airlines- pre-petition',
'subaru of new england',
'anr pipeline',
'lowes companies inc',
'east air corporation',
'sms investments llc',
'commutair',
'massmutual',
'aviation technologies, inc.',
'whirlpool corporation',
'hageland aviation services',
'tpg global, llc',
'l-3 vertex',
'sa aircraft services',
'socal jet inc.',
'summit air ambulance',
'ds technologies llc',
'nexair avionics llc',
'the j.m. smucker co.',
'federated hermes, inc',
'aerovision component services',
'tti coreporate hangar',
'ati jet charter',
'vf corporation',
'eclipse aerospace',
'lone palm air llc',
'north american jet charter group',
'aic maintenance inc.',
'sj management, llc',
'mesa airlines inc.post petition',
'pinnacle aviation',
'wing aviation charter services llc',
'analar corporation',
'cockrell resources, inc.',
'boulder aviation management',
'apr aviation',
'club jet',
'harco aviation',
'coastal aircraft maintenance',
'nevitt aircraft, inc.',
'camm air',
'vegso aviation inc',
'aero service center llc',
'petrolift aviation services, inc',
'mountain aviation, inc',
'silver air',
'toledo jet center',
'ls air maintenance',
'colonial air inc',
'chautauqua county sheriff',
'advanced drainage systems,inc',
'kapco brea',
'sixty something llc',
'rotortech services inc.',
'segers aero corporation',
'central jet services',
'hawaii island air inc-pre-petition',
'valley air crafts',
'starflite aviation',
'l-3/vertex aerospace',
'aviation management group',
'ctp aviation',
'first call international',
'topeka air ambulance',
'mraf llc',
'air gato enterprises, inc.',
'one thirty nine limited',
'eclipse management, llc',
'willis lease finance corporation',
'ssi aviation group, llc',
'tri state g & t',
'rodney c.robertson & john k.miller',
'new mexico state police',
'ozark air services,inc',
'jet center mfr',
'accent air',
'aircraft associates',
'precision aircraft management',
'curran mustang llc',
'grand canyon airlines inc',
'hageland aviation service',
'clay lacy aviation',
'aventure aviation',
'hawker beechcraft services inc',
'spectra energy',
'jet services, inc',
'schweitzer engineering',
'schweitzer engineering',
'nextera energy inc',
'united parcel service co.',
'bae systems, inc.',
'jetstream aviation, inc',
'msp aero',
'bombardier customer services-tucson',
'the j.m. smucker co',
'n1 llc',
'vail valley jet center',
'optimum aircraft services, llc',
'southern aircraft services',
'hawker beechcraft parts&dist',
'mobile aircraft services',
'boca aircraft maintenance',
'aar airlift',
'global filtration inc',
'commuter air technology, inc',
'executive air services, llc',
'lenox aviation, llc',
'mdg airline services inc',
'infotech associates inc',
'aerospace technologies',
'aviation repair & service llc',
'prime turbines llc',
'aerojet services, inc.',
'lufthansa technik/logistik',
'million air houston',
'southern jet management inc',
'new york state police aviation',
'lee county mosquito',
'solairus aviation',
'delta fox aviation',
'corporate air llc',
'lewis energy',
'pentastar aviation llc',
'k&p flying service,inc',
'wichita citation service center',
'kingfisher air service',
'aircraft services group, inc',
'henrietta bldg supplies inc',
'interstate aviation inc',
'intermodal aviation inc',
'shoreline aviation inc',
'priority air charter llc',
'watermakers air',
'capital aviation- pre-petition',
'wyoming department of',
'stevens aviation',
'jet air inc',
'bill dause',
'national jets inc',
'underhill holdings llc',
'motley rice llc',
'avmats',
'ultimate aviation solutions',
'alaska air transit',
'federal aviation administration',
'mid america jet',
'dhl network operations',
'united technologies flight',
'stampede aviation llc',
'avia source, inc.',
'heliworks inc.',
'southeastern asset mgmt/sms',
'idea builders engineering',
'american jet charter, inc.',
'blue ridge airport authority',
'marvin windows and doors',
'thompson flying service llc',
'airmark international (amacpi)',
'jet support services inc',
'worthington industries',
'brite air parts',
'western air international',
'golden state jet llc',
'bmg aviation, inc',
'flightsafety international',
'devils lake aero service',
'redding jet center',
'n583kd, llc',
'tidewater inc- pre pettition',
'verti-flight services,inc',
'comlux aviation services llc',
'aircraft specialists, inc.',
'sherwin williams',
'emerald coast aviation',
'truist bank',
'idea builders engineering inc.',
'bastille energy corporation',
'signature technicair',
'quantum air services inc.',
'd.w. morgan company',
'trans aero helicopters',
'american mine research inc.',
'professional jet, inc.',
'panorama investments llc',
'humana inc.',
'logistics business services',
'jetsuite',
'kalispell regional medical center',
'csp&p',
'montana aircraft, inc.',
'hsi turbines, inc.',
'via feliz ii llc',
'edwards rotorcraft solutions inc.',
'international paper company',
'trimec aviation',
'atlantic aviation - portland',
'aero products component services',
'aircraft turbine works inc.',
'air concepts international',
'whirlwind aviation, inc',
'golden west airlines',
'american airlines inc.',
'buena suerte llc',
'fhc flight services inc',
'hinson corporate flight services',
'northwest flyers, inc',
'shodeen group',
'ggs management, inc',
'jet aviation flight services - adp',
'aviotrade,inc',
'aerial crop services, llc',
'republic airways holding inc.',
'superior aviation solutions',
'elbit sysytems of america',
'meridian jet center',
'heritage aviation',
'pofolk aviation hawaii inc',
'freedom aviation',
'ecolift corporation',
'executive air charter, llc',
'pac aviation international,inc',
'mid america jet',
'xwilks brothers llc',
'tansa export inc',
'professional technology repairs',
'jack henry & associates, inc',
'eldec corporation',
'signature technicair',
'rotorcraft services group',
'shey systems, inc',
'aersale, inc',
'arrow dynamics llc',
'p&s agricultural services',
'ace flight operations',
'guardian jet, llc',
'gold coast helicopters inc.',
'technicair oma',
'ams',
'wayfarer ketch management',
'elliott aviation of des moines inc',
'hubbard broadcasting inc',
'ballard aviation, inc',
'constant aviation',
'united therapeutics corp',
'freeman group llc',
'winner aviation corporation',
'vision aero inc',
'noble eagle engineering',
'seal dynamics',
'guardian flight, llc',
'capital aviation- pre-petition',
'mosavia corporation',
'san francisco helicopters',
'albertson’s, llc.',
'air medical resource group',
'total air group',
'kingfisher air services',
'jet icu',
'flightcheck llc',
'american aviation supplies, llc',
'emc aerospace, inc.',
'transcanada anr pipeline',
'carolina aviation technical service',
'sedgwick azure, inc',
'world aviation logistics, llc',
'terrapin aircraft llc',
'bombardier aviation services',
'textron aviation service center',
'smart jet aviation, llc',
'forte aviation parts inc.',
'n1 llc',
'emerson air service inc',
'north american spares,ltd',
'ga telesis, llc.',
'mac aerospace corp.',
'3c aviation',
'greenpoint technologies inc.',
'surf airlines llc',
'nobleflight',
'dar international, inc',
'eva air, llc',
'sthky air, llc',
'georgetown turbine service',
'jarden corporation',
'new york yankees partnership',
'reach air medical services',
'bel air, llc',
'dynatech international llc',
'abateco',
'ace aviation',
'lima ny d/b/a fly the whale',
'crs jet spares',
'phoenix air group, inc.',
'sl management llc',
'kalitta charters, llc',
'primestar aviation',
'aic global holdings inc.',
'genesis aircraft parts',
'honaker aviation',
'quality controlled',
'kalitta air, llc',
'team jas, inc.',
'vas aero services llc',
'hawk aviation la-llc',
'latitude 33 aviation llc',
'jet aviation flight services inc.',
'fimco industries',
'blackfin aviation',
'j.a. air center',
'science and engineering services',
'flextronics photonics ppt inc',
'sonic automotive aviation',
'aircraft structures international',
'sanmar corporation',
'air choice one',
'platina investment corp.',
'139 limited',
'northstar aviation services, llc',
'n767cj  llc',
'ppg industries',
'crestwood technology group',
'paradigm jet management',
'hammond air center',
'air 7',
'morgan aviation co inc.',
'keystone aviation kuao',
'american jet charter',
'tec equipment inc.',
'two bear air',
'agency for defense development',
'macquarie rotorcraft leasing, inc.',
'shamrock capital corp., llc',
'heico component repair group',
'ecoservices llc',
'lookfar aviation',
'robinson aviation, llc.',
'royal air freight, inc.',
'pnb aero',
'pathfinder aviation inc',
'jackson jet center',
'bob jones university',
'perform air international inc',
'signature technicair',
'sentry insurance company',
'quantum spatial',
'custom jet charters llc',
'planesmart aircraft services llc',
'late aircraft repair llc',
'hawk air, llc',
'signature technicair',
'sica llc',
'live oak bank',
'ah aero services llc',
'flight group corporation',
'texas pneumatic systems, inc',
'andrew bettis aviation',
'stat industry inc',
'heinen brothers agra service',
'erickson helicopters-pre-petition',
'airspeed aviation llc',
'axcess aviation',
'aero technical components',
'herndon products, inc.',
'viper capital logistics',
'lanigan holdings llc',
'united a/l',
'north star aerospace',
'tallamond aero',
'southern spares services, llc.',
'jackson family wines, inc.',
'pacific wings, llc',
'api group inc.',
'sams electronic tech inc.',
'smooth landing, llc',
'priority jet',
'lincoln skyways, inc',
'atlas air, inc',
'the boler company',
'northpoint aviation',
'premier aviation overhaul center lt',
'summit aviation inc',
'ncfe air huron',
'hawaii life flight',
'sanders international',
'surf air inc.',
'atlanta turbine management',
'netjets aviation inc.',
'sa aircraft services',
'general transervice, inc.',
'tropic air',
'stebbins aviation, inc.',
'performance flight',
'cvs pharmacy inc',
'precision aircraft maintenance',
'sierra west airlines',
'mokulele flight service in',
'bv aviation iv, llc',
'master tronics',
'signature technicair',
'lincoln financial group',
'air spray usa',
'meyer tool inc.',
'lv5 aviation, inc.',
'farm ag enterprises,llc',
'diversified aero services inc.',
'pacific air holdings',
'boutique air, inc.',
'bg aero llc',
'c & l aviation services',
'boutique air',
'air parts services & supplies ltd',
'brownstone aviation, llc.',
'apache corp',
'flying w, llc',
'luck stone corporation',
'n179lf, llc',
'nicholas air',
'suburban properties 3, llc',
'cascade aircraft management',
'deblois aerospace',
'castlelake',
'aero-link arizona, inc.',
'united technologies-utflight',
'airspeed aviation llc',
'chattanooga aero service',
'napa jet center',
'act supply corporation',
'aero parts and services, llc',
'air evac ems, inc.',
'air tech international, inc.',
'airborn electronics, inc.',
'aircraft & engine parts, llc.',
'aircraft engines technologies inc.',
'airparts company, inc.',
'alaris aerospace systems llc',
'alaska central express',
'api aerospace products',
'army fleet support, llc',
'asap semiconductor',
'astro trading & technologies corp.',
'atlas aerospace accessories, inc.',
'august resources, llc',
'av-air, inc.',
'avecs global, inc',
'avtek group llc',
'aw-tronics llc',
'bas-bdl',
'bisco industries, inc.',
'br aviation investments llc',
'caravan international corp',
'chicago executive service ctr',
'cuana components',
'delta aviation, inc.',
'diversified aero services, inc',
'dmi aviation sales, corp.',
'electreq, inc.',
'e.t. mechanical llc',
'ethiopian airline enterprise',
'faa fifo btl',
'great lakes turbines, inc',
'greer industries, inc.',
'group vi, llc',
'hangar one of california, inc.',
'international aircraft parts',
'international component repair',
'intertrade',
'j.g.b. enterprises, inc.',
'jamco america, inc',
'kirkham helicopter',
'landing gear technologies, llc',
'signature technicair',
'linear air',
'miami inter air, inc.',
'midwest aerospace, ltd',
'netjets aviation, inc',
'north slope borough',
'omnia',
'oeco, llc dba pacific scientific',
'principal financial group',
'projects, inc',
'signature technicair',
'skydive guam inc',
'south aviation',
'specialized aircraft services',
'stair cargo inc.',
'superior aviation solutions',
'tame airlines c/o provex inc',
'team aero, llc',
'the nordam group',
'topeka air ambulance',
'trek aviation, llc',
'united services automobile assn',
'valcor engineering corporation',
'vectored solutions',
'wencor, llc',
'wright air service, inc.',
'baron & budd',
'baddox llc',
'mustang systems llc',
'aero star aviation',
'american charter services llc',
'leon helicopter one, llc',
'baker aviation llc',
'gem city properties llc',
'sherr & company inc',
'lone wolf aviation llc',
'global aviation technologies',
'ibw air services llc',
'jotts llc',
'nation flight llc',
'daher socata north america',
'enemy aircraft, llc',
'florida technologies',
'manas technologies',
'miami aviation specialists',
'steiner aviation international inc',
'denver air support, inc.',
'rod robertson enterprises, inc',
'sky harbor aviation',
'van daele development, inc.',
'union pacific railroad',
'arms international',
'skymark aviation',
'316 aviation company inc.',
'broadie’s aircraft',
'cobalt aviation ii llc',
'quality group of companies, llc',
'idg usa, llc',
'arrowhead products',
'jd plane repair',
'lancaster purchasing services',
'reach air medical services llc',
'mobile jet maintenance',
'microlinz llc',
'piedmont aviation component service',
'r&c aviation inc',
'flitewing inc.',
'longhorn regional service center',
'bb one llc',
'clyde companies, inc',
'frayer jets 1, llc',
'jet midwest technik',
'sonicare solutions inc.',
'plane sense llc',
'pierce aviation',
'tnc aero, inc.',
'city wings inc.',
'north american surveillance',
'air services limited',
'the bank of new york mellon',
'surf air inc',
'pathfinder aviation',
'aviation supply',
'mokulele airlines',
'skywest aviation, inc.',
'sound inpatient physicians, inc.',
'inventory navigators, llc',
'nasa',
'compass airlines',
'victory aviation services inc.',
'black diamond',
'american airlines',
'bankaire inc.',
'american aircraft maintenance',
'aero tech services',
'alaska aircraft sales',
'seaman corporation',
'huntsville aviation llc',
'wencor, llc',
'diamond a administration company',
'kenn aire corporation',
'air riders aviation inc',
'edo corporation',
'million air',
'signature technicair',
'constellation productions, inc',
'airgroup dynamics, inc.',
'civilon llc',
'aviation performance solutions llc',
'sgmj llc',
'kansas city life insurance',
'aero controls, inc.',
'conquest aerospace services, llc',
'a-ron resources llc',
'diamond aviation llc',
'meregrass',
'autonation, inc.',
'aeronautical services of greenwood',
'sklar transport co.',
'r & b aircraft supply, inc.',
'precision aviation services',
'lan cargo',
'habco industries llc',
'english field aviation',
'south florida jet center',
'challenger aviation services',
'allied international support inc.',
'epic flight support',
'peninsula avionics, inc.',
'seaflight mx c/o st thomas jet cent',
'hill top holdings',
'us airways',
'ineo global support inc',
'century helicopters, inc',
'field aerospace',
'amur helicopter financial services',
'dynamic aviation',
'tri valley air, llc',
'woodward inc.',
'able engineering',
'aerotec international',
'hawaiian airlines purchasing',
'expressjet airlines',
'delta airlines inc.',
'american airlines inc',
'logistics specialties, inc',
'nicholas air',
'aj aviation usa llc',
'mach 1 aircraft maintenance inc',
'texas aircraft services llc',
'air resource group',
'rgb enterprises, llc',
'dallas executive aircraft service',
'marion county sheriff’s office',
'jet blue airways',
'ati engineering services llc',
'aero precision',
'jag aviation',
'fbi/sfou/doj',
'boneal incorporated',
'amr services inc.',
'abc components',
'aeropartners america inc',
'jetblue airways corp.',
'j r helicopters llc',
'sterling air service',
'wells enterprises, inc.',
'ams industries, llc',
'gecas asset management svcs',
'transatlantic spares & services inc',
'smc aviation inc.',
'aero part service inc',
'aerospace precision inc',
'harter industries inc',
'astro instruments services corp',
'alpha aircraft systems inc',
'avio diepen inc',
'electrofilm manufacturing co',
'fastenal',
'l j walch co inc',
'continental aircraft support, inc.',
'mti aviation inc',
'summit aerospace inc',
'tacor inc',
'timco lake city',
'viman aviation inc',
'pneu tech aerospace inc',
'silver wings aerospace',
'skylink inc',
'fischer properties',
'devex development export assoc. inc',
'gasair, llc',
'copper country aero, inc',
'api group inc',
'technicair signature',
'latam airlines group s a',
'union pacific railroad',
'atlantic diving supply, inc.',
'vantage ic, llc',
'advance air services inc',
'prime turbines phoenix',
'future aviation inc',
'southwest airlines co',
'sentry aerospace corp',
'ga telesis component repair',
'jansen aircraft systems controls',
'aviosupport inc',
'paz aviation inc',
'jet parts inc',
'great lakes global aviation logisti',
'goodrich control sys',
'aog air intl',
'bf aerospace llc',
'salt river aviation llc',
'airborne maintenance and engr',
'united airlines inc',
'global air services llc',
'aireps inc',
'baron group llc',
'classic aviation llc',
'corporate jet support',
'delta group electronics',
'envoy air inc',
'goodrich aerostructures group',
'regional one',
'zga aircraft parts',
'shoreline aviation',
'bronze elk enterprises, llc',
'med-craft inc',
'excelsis, llc',
'raisbeck engineering, inc.',
'muy consulting inc',
'eclipse jet 77 llc',
'trmsi inc',
'brunswick corporation',
'japan airlines co., ltd',
'houston aeromotive',
'aero parts management',
'jetworx',
'take flight aviation',
'fibercraft',
'piedmont propulsion systems llc',
'1st choice aerospace',
'airfoil technology',
's&s aviation',
'jma energy company llc',
'challenger aviation services',
'ranger air',
'exec aero llc',
'altum aerospace',
'osnijenpri parts supply and repair',
'cae usa inc.',
'cambridge flight support',
'n1 llc',
'things with wings, llc',
'aeross parts and supply',
'nassau county police aviation',
'167 east 63rd helicopters llc',
'expressjet airlines',
'prime aerospace usa, llc',
'eagle industries international, inc',
'vc display inc',
'avionic industries, inc.',
'kapco-global ct',
'aerovision aircraft services, llc',
'compass airlines, inc',
'century aviation',
'apex aviation',
'reliable jet maintenance',
'xcel energy services, inc.',
'stock aviation inc',
'saturn aviation',
'business jet center',
'lotus aero international, inc.',
'turbine engine consultants, inc.',
'maxmen aviation, llc',
'mt texas llc',
'echo alpha air, llc',
'michigan state police',
'athens jet prop, inc',
'itt aerospace controls',
'regional airline support group',
'jet aviation services, inc',
'embraer aircraft maintenance',
'republic airline, inc.',
'signature technic air',
'beechcraft defense company',
'alpha 1 aviation llc',
'ncp freedom, llc',
'avion systems inc.',
'avcorp international, inc.',
'fly the whale',
'forum air, llc',
'conquest aerospace services, llc',
'general atomics aeronautical system',
'sky tech solutions llc',
'rl carriers',
'lockheed martin corp',
'rvr aviation llc',
'taca inl airlines sa',
'bny mellon',
'amt program',
'proteus energy, llc',
'aaf spares llc',
'surf air',
'airpac airlines',
'us milgrp taft avn team 3',
'american airlines',
'saab defense and security usa',
'pae aviation and technical services',
'avianca inc.',
'flighttime enterprises inc',
'uline inc.',
'leonardo helicopters awpc',
'aviation management sales',
'palmetto express llc',
'motivax trading corp',
'pdkaa 250 hm partners llc',
'associated aviation enterprises llc',
'avionictech (sunelenus)',
'dow chemical company',
'aero applicators inc.',
'brodersen robert trustee',
'vss logistics',
'shark one, llc',
'vista aviation, inc.',
'ots aircraft holdings llc',
'kodiak aircraft company inc',
'extreme aviation services',
'tekair llc',
'valstar inc.',
'dejaero',
'southern airways express',
'orin acker',
'windy city helicopters',
'solair group, llc',
'mighty mouse aviation',
'north flight aero med',
'leidos innovations corp',
'phast parts enterprises llc',
'executive business aviation',
'sevenbar aviation',
'jag aero',
'liberty global inc',
'dallas jet international lp',
'premier air international llc',
'ametek mro florida inc.',
'mar aviation',
'circle air group',
'jkp enterprises inc.',
'xsyn corp.',
'global parts support, inc',
'national aviation, inc',
'htf aerospace inc',
'jwc interest llc',
'rdd enterprises',
'circle air group llc',
'fly advanced',
'khan aviation',
'precision turbines inc.',
'erickson helicopters-post-petition',
'odyssey aviation llc',
'xsyn inc',
'eka systems',
'j & s plating and repair',
'rair maintenance llc',
'northwood aero service',
'toms aircraft',
'state of north carolina',
'tsg holdings, llc',
'aero star aviation',
'mid america apartments',
'learjet leasing, llc',
'aeroptic llc',
'stratosphere aviation',
'aerospares, llc',
'k2m-global, llc',
'todo usa',
'bayview aviation',
'next mro',
'biourja trading llc',
'downs food group',
'air commercial jet',
'nelson parts llc',
'infinity aircraft services',
'flight level zero llc',
'us assets recovery llc',
'fb aviation',
'coppage farm services inc',
'celestial aviation inc',
'mhd rockland',
'merlin global services',
'francis dunleavy',
'hbp 131, llc',
'execjet1, llc',
'aog parts & logistics inc',
'fossco inc',
'chautauqua aircraft sales, inc',
'mariposa capital llc',
'mobile jet care',
'obrien flying service inc',
'taylor marine',
'323 global sourcing',
'turbineaero engines technics inc',
'pv transport inc',
'precision aero technology',
'barrett business services inc.',
'first class aviation, inc.',
'aerospace accessory services, inc',
'sky tech solutions llc',
'aero south florida, inc.',
'45 north aviation llc',
'crop jet aviation, llc',
'ground solution inc.',
'renshaw automotive group',
'rocky mountain turbine services',
'ja air centers',
'copper state turbine engine company',
'klx aerospace solutions defense llc',
'schmidt aviation, inc',
'cjj management, llc',
'tail wind air service',
'orbital atk',
'zip aviation',
'guacamole management, llc',
'l & m radiator',
'spitfire usa limited',
'encompass aviation llc',
'wilsonart llc',
'zephyr services, llc',
'velocity aerospace - nmb',
'solana repair services, llc',
'flight equiptment inc',
'missouri aviation services, llc',
'dean oystreck',
'ag aircraft, inc',
'elite flight jets',
'bnt international corp.',
'professional aviation associate',
'jm aviation company llc',
'royal pacific air',
'pinellas county sheriff’s office',
'grand canyon airlines inc',
'sn 154 llc',
'petrichor industries',
'altronix',
'allegiant air',
'eagle eye aviation',
'onav, llc',
'dynatech international llc',
'aar allen asset management',
'idag llc',
'first call aviation',
'jag aero solutions',
'elite aircraft services llc.',
'ipd aerospace, inc.',
'e5 ventures, llc',
'hawaii island air inc-post-petition',
'forced aeromotive technologies, inc',
'n328rp aviation llc',
'fcb blue llc',
'saxet consulting, llc',
'elite jets chater, llc',
'the international defense',
'cambridge international',
'unique airmotive services, llc',
'k&b aircraft leasing and services',
'patton aircraft repair llc',
'a1 aerospace inc',
'lejeune aerial applications llc',
'southern sky aviation',
'evergreen flying services, inc',
'western airways',
'global connects llc',
'kenn air corp.',
'desert jet',
'aviation specialties unlimited, inc',
'blackfriars aviation llc',
'jet access aviation',
'premier aviation services',
'elite jet solutions',
'north coast air care',
'crowne management llc',
'quality corporate aircraft services',
'excel leasing, llc',
'aerobrigham, llc',
'rmr capital aviation llc',
'davic group llc',
'ceoc, llc',
'sun aviation',
'aviation trade inc.',
'acrisure aircraft 233, llc',
'jt aerospace',
'boman & kemp manufacturing',
'merrill field instruments',
'northwestern mutual',
'kag services llc',
'satcom direct',
'echo aviation, llc',
'victory air, llc',
'conagra brands',
'bg logistics holdings, llc',
'northeast air repair, llc',
'm1 support services',
'aar government services inc',
'bt aero',
'airspeed aviation llc.',
'us milpack & mfg corp',
'aerospace access corporation',
'gv aerospace llc',
'flight metrics',
'general mro aerospace inc',
'rh aviation, llc',
'apri aviation, inc.',
'dynatech intl',
'blue aerospace',
'turtle speed, llc',
'jmi services, llc',
'm1 support services',
'm1 support services',
'zip aviation',
'interbyte',
'ds advisors',
'appalachian aero group',
'fhc flight services',
'rising sun aviation llc.',
'legacy air, inc',
'east west helicopter inc.',
'fi aerospace solutions, inc.',
'cutter aviation denver',
'skyone holdings',
'city wings d/b/a sea flight',
'sterling aeronautics llc',
'donner air 261, llc',
'vaughn college',
'retail business services, llc',
'nyc department of environmental pro',
'hantz air llc',
'airshare',
'conmeta inc.',
'iex helicopters',
'miles to go',
'pfs capital, llc',
'pc12 leasing llc',
'tailwinds air',
'agtegra cooperative',
'west main ii llc',
'ks air 3-7-12 v, llc',
'holdrege aviation',
'northwest seaplanes inc',
'fire eagle, inc',
'corr aviation',
'solana repair services, llc',
'collins aerospace',
'axtmann holdings inc',
'av8 mro',
'wescam usa inc',
'aviotrade inc',
'henry’s aerial service inc.',
'critical air response ent. llc',
'executive jet management',
'flight director, inc.',
'mi aviation holdings, llc',
'nci building system',
'q-jet',
'aviation maintenance professionals',
'air commercial jet corp.',
'phoenix investments, inc',
'americo services inc.',
'sentinel aerospace, llc',
'elite jet solutions, llc',
'grant aviation inc',
'island air service',
'aviation rotables llc',
'steiner aviation',
'trueaero, llc',
'revellie air',
'bidzy ta hot aana corporation',
'sai flight companies',
'corporate jet leasing co. llc',
'jet aviation',
'asset conversion services, inc.',
'arizona game and fish department',
'united aero group llc',
'psa commerce & services llc',
'abc intercargo',
'rlc aviation, llc',
'solairus aviation',
'huston2009 llc',
'pam jets',
'sl management group',
'thayer acquisitions llc',
'spring city aviation',
'ag air aircraft, inc',
'san diego jet management, llc',
'keller supply company',
'paradise jets',
'aeromax industries, inc',
'aloia aerospace inc',
'savaren corp aircraft services',
'gmj air shuttle, llc',
'texas aircraft services, llc',
'american equity',
'safran electrical & power llc',
'nicholas services llc',
'cima aviation',
'mach.81, llc',
'time to travel aviation llc',
'hypersonic force llc',
'northern air maintenance service',
'avianca inc',
'lafayette aircraft services, llc',
'gee 6 llc',
'h k aviation corp',
'mpac aviation services llc',
'northwind aviation',
'dcjets services llc',
'makers air',
'dauntless air',
'360 aerospace llc',
'mirada manager',
'big canopy, llc',
'extreme air llc',
'airways aviation center',
'national supply, llc',
'44sh, llc',
'viking cake holdings ii',
'flytat llc',
'h4t corp',
'putnam aircraft consulting and',
'tamiami intl sales corp',
'all-system aerospace intl inc',
'arkansas childrens hospital',
'dhl aviation americas, inc.',
'broward county sheriffs office',
'turbo resources intl',
'earls flying service llc',
'loyds aircraft maintenance',
'thomass aircraft supplies',
'broadies aircraft',
'jet-care intl inc.',
'fitchs flying service',
'arlins aircraft service, inc.',
'j.r.s sky inc.',
'fix n to fly inc',
'youngs aircraft repair',
'chautauqua county sheriffs dept.',
'fly beckys air',
'zaxbys franchising llc.',
'kern county sheriffs office',
'tech-avia intl ltd',
'jerrys aircraft service',
'butte county sheriffs department');
