CREATE TABLE ADP_STOCKEXT(
	PARTNUMBER char(30) NOT NULL,
	SUBP char(5) NOT NULL,
	FIELD1 varchar(60) NULL,
	FIELD2 varchar(60) NULL,
	FIELD3 varchar(60) NULL,
	FIELD4 varchar(60) NULL,
	FIELD5 varchar(60) NULL,
	FIELD6 varchar(60) NULL,
	FIELD7 varchar(60) NULL,
	FIELD8 varchar(60) NULL,
	FIELD9 varchar(60) NULL,
	FIELD10 varchar(60) NULL,
	FIELD11 varchar(60) NULL,
	FIELD12 varchar(60) NULL,
	FIELD13 varchar(60) NULL,
	FIELD14 varchar(60) NULL,
	FIELD15 varchar(60) NULL,
	FIELD16 varchar(60) NULL,
	FIELD17 varchar(60) NULL,
	FIELD18 varchar(60) NULL,
	FIELD19 varchar(60) NULL,
	FIELD20 varchar(60) NULL,
	RECLOCK char(4) NULL,
	ADDED_USR char(4) NULL,
	ADDED_DTE datetime NULL,
	UPDATED_USR char(4) NULL,
	UPDATED_DTE datetime NULL,
CONSTRAINT STOCKEXT_PK PRIMARY KEY (PARTNUMBER,SUBP)
);
