CREATE or replace TABLE adp_SHIPTO(
	SHIP_TYPE char(1) not NULL,
	ACCTNO char(12)  not NULL,
	SUBC char(5)  not NULL,
	SHIP_NO smallint  NULL,
	SHIPVIA char(5) NULL,
	SHIP_CODE varchar(10) NULL,
	SPEC2000 varchar(10) NULL,
	NAME varchar(60) NULL,
	ADR1 varchar(40) NULL,
	ADR2 varchar(40) NULL,
	ADR3 varchar(40) NULL,
	CITY varchar(30) NULL,
	STATE char(4) NULL,
	COUNTY varchar(20) NULL,
	ZIP char(12) NULL,
	COUNTRY varchar(40) NULL,
	REGION char(5) NULL,
	TEL_PFIX char(6) NULL,
	TEL1 char(40) NULL,
	TEL1_EXT varchar(10) NULL,
	TEL2 char(40) NULL,
	TEL2_EXT varchar(10) NULL,
	FAX1 char(40) NULL,
	FAX2 char(40) NULL,
	SITA varchar(20) NULL,
	INTERNET varchar(100) NULL,
	WEB_SITE varchar(100) NULL,
	CCODE char(5) NULL,
	INVOICE_TYPE char(1) NULL,
	REGISTRATION_NO char(30) NULL,
	REGISTRATION_UPD datetime NULL,
	REGISTRATION_VALID datetime NULL,
	PAD text NULL,
	MISC1_TYPE char(1) NULL ,
	MISC2_TYPE char(1) NULL ,
	MISC3_TYPE char(1) NULL ,
	MISC4_TYPE char(1) NULL ,
	MISC5_TYPE char(1) NULL ,
	MISC6_TYPE char(1) NULL ,
	MISC1_PERC decimal(28, 9) ,
	MISC2_PERC decimal(28, 9) ,
	MISC3_PERC decimal(28, 9) ,
	MISC4_PERC decimal(28, 9) ,
	MISC5_PERC decimal(28, 9) ,
	MISC6_PERC decimal(28, 9) ,
	MISC1_PRN char(1) ,
	MISC2_PRN char(1) ,
	MISC3_PRN char(1) ,
	MISC4_PRN char(1) ,
	MISC5_PRN char(1) ,
	MISC6_PRN char(1) ,
	MISC1_TTL char(1) ,
	MISC2_TTL char(1) ,
	MISC3_TTL char(1) ,
	MISC4_TTL char(1) ,
	MISC5_TTL char(1) ,
	MISC6_TTL char(1) ,
	LABOR_MISC1_TTL char(1) ,
	LABOR_MISC2_TTL char(1) ,
	LABOR_MISC3_TTL char(1) ,
	LABOR_MISC4_TTL char(1) ,
	LABOR_MISC5_TTL char(1) ,
	LABOR_MISC6_TTL char(1) ,
	SUBT_TAX_A char(1) ,
	SUBT_TAX_B char(1) ,
	SUBT_TAX_C char(1) ,
	M1_TAX_A char(1) ,
	M1_TAX_B char(1) ,
	M1_TAX_C char(1) ,
	M2_TAX_A char(1) ,
	M2_TAX_B char(1) ,
	M2_TAX_C char(1) ,
	M3_TAX_A char(1) ,
	M3_TAX_B char(1) ,
	M3_TAX_C char(1) ,
	M4_TAX_A char(1) ,
	M4_TAX_B char(1) ,
	M4_TAX_C char(1) ,
	M5_TAX_A char(1) ,
	M5_TAX_B char(1) ,
	M5_TAX_C char(1) ,
	M6_TAX_A char(1) ,
	M6_TAX_B char(1) ,
	M6_TAX_C char(1) ,
	TAX_A_CODE char(5) NULL,
	TAX_B_CODE char(5) NULL,
	TAX_C_CODE char(5) NULL,
	GL_ACCOUNT char(15) NULL,
	TAX_A_GL char(15) NULL,
	TAX_B_GL char(15) NULL,
	TAX_C_GL char(15) NULL,
	TAX_A_TTL char(1) ,
	TAX_B_TTL char(1) ,
	TAX_C_TTL char(1) ,
	TAX_ON_TAX_B char(1) ,
	ISACTIVE char(1) ,
	PAID_BY_WIRE char(1) ,
	PAID_BY_ACH char(1) ,
	SPC_2000_C varchar(30) NULL,
	RECLOCK char(4) NULL,
	ADDED_USR char(4) NULL,
	ADDED_DTE datetime NULL,
	UPDATED_USR char(4) NULL,
	UPDATED_DTE datetime NULL,
constraint SHIPTO_PRK primary key (SHIP_TYPE , ACCTNO, SUBC,SHIP_NO)
);
