CREATE TABLE ADP_CUSTVENDSETUP(
	ACCTNO char(12) NOT NULL,
	SUBC char(5) NOT NULL,
	CUST_VEND char(1) NOT NULL,
	RCV_OVER_SHIP decimal(28, 9) ,
	SHIPTO smallint ,
	BILLTO smallint ,
	PAYTO smallint ,
	SHIP_DEF_NO smallint ,
	BILL_DEF_NO smallint ,
	PAY_DEF_NO smallint ,
	PAY_US char(4) NULL,
	SHIP_DEF_SUBC char(5) NULL,
	BILL_DEF_SUBC char(5) NULL,
	PAY_DEF_SUBC char(5) NULL,
	COMPANYNO smallint NULL,
	DIVISION char(5) NULL,
	DEPART char(5) NULL,
	LANG_KEY char(5) NULL,
	FORM_1099 char(1) ,
	FORM_1099TYPE char(2) NULL,
	DISC_CODE char(5) NULL,
	REGISTRATION_NO char(30) NULL,
	REGISTRATION_UPD datetime NULL,
	REGISTRATION_VALID datetime NULL,
	HOLD char(1) ,
	HOLD_DATE datetime NULL,
	HOLD_BY char(4) NULL,
	APPROVED char(1) ,
	APPROVED_DATE datetime NULL,
	APPROVED_BY char(4) NULL,
	ULINES char(1) ,
	PRINT_PN char(1) ,
	PRINT_OUR char(1) ,
	PICK_TICKET_PER_PN char(1) ,
	SUM_DOC_LINES char(1) NULL,
	CCODE char(5) NULL,
	TERM_CODE char(5) NULL,
	CREDIT decimal(28, 9) ,
	GLOBAL_CREDIT char(1) ,
	WGHT_TO char(5) NULL,
	VOL_TO char(5) NULL,
	LENGTH_TO char(5) NULL,
	SHIP_COMPLETE char(1) ,
	POST_SHIP_DOC char(1) ,
	POST_RECV_HDR char(1) ,
	AUTO_RFQ_DEALERS char(1) NULL,
	INV_TYPE char(1) NULL,
	ACCOUNT_TYPE char(5) NULL,
	ACCOUNT_RATE char(5) NULL,
	PRIORITY char(5) NULL,
	COPY_PRIORITY char(1) ,
	EARLY_SHIPMENT char(1) ,
	DAYS_BEFORE_SHIPPING smallint ,
	SHIPVIA varchar(20) NULL,
	FOB varchar(20) NULL,
	FOB_LBL char(10) NULL,
	GL_ACCOUNT char(15) NULL,
	LATE_CHARGE_GL_ACCOUNT char(15) NULL,
	CURENCY_CONV char(5) NULL,
	MIN_ORDER_LINE decimal(28, 9) ,
	MIN_ORDER decimal(28, 9) ,
	PRICETBL_CELL smallint NULL,
	QT_TYPE_DEF char(2) NULL,
	SO_TYPE_DEF char(2) NULL,
	RF_TYPE_DEF char(2) NULL,
	PO_TYPE_DEF char(2) NULL,
	IMP_EXP_FILETYPE char(1) NULL,
	SMAN1_CODE char(4) NULL,
	SMAN2_CODE char(4) NULL,
	SMAN3_CODE char(4) NULL,
	SMAN4_CODE char(4) NULL,
	SMAN5_CODE char(4) NULL,
	AGENT_CODE char(4) NULL,
	SMAN1_PERC decimal(14, 9) ,
	SMAN2_PERC decimal(14, 9) ,
	SMAN3_PERC decimal(14, 9) ,
	SMAN4_PERC decimal(14, 9) ,
	SMAN5_PERC decimal(14, 9) ,
	AGENT_PERC decimal(14, 9) ,
	ADD_AGENT_PRICE char(1) ,
	SMAN1_NG char(1) ,
	SMAN2_NG char(1) ,
	SMAN3_NG char(1) ,
	SMAN4_NG char(1) ,
	SMAN5_NG char(1) ,
	SMAN1_DOCLN char(1) ,
	SMAN2_DOCLN char(1) ,
	SMAN3_DOCLN char(1) ,
	SMAN4_DOCLN char(1) ,
	SMAN5_DOCLN char(1) ,
	DISC_TYPE char(1) ,
	DISC_DOCLN char(1) ,
	DISC_PERC decimal(28, 9) ,
	MISC1_DOCLN char(1) ,
	MISC2_DOCLN char(1) ,
	MISC3_DOCLN char(1) ,
	MISC4_DOCLN char(1) ,
	MISC5_DOCLN char(1) ,
	MISC6_DOCLN char(1) ,
	MISC1_TYPE char(1) ,
	MISC2_TYPE char(1) ,
	MISC3_TYPE char(1) ,
	MISC4_TYPE char(1) ,
	MISC5_TYPE char(1) ,
	MISC6_TYPE char(1) ,
	MISC1_PERC decimal(28, 9) ,
	MISC2_PERC decimal(28, 9) ,
	MISC3_PERC decimal(28, 9) ,
	MISC4_PERC decimal(28, 9) ,
	MISC5_PERC decimal(28, 9) ,
	MISC6_PERC decimal(28, 9) ,
	MISC1_PRN char(1) ,
	MISC2_PRN char(1) ,
	MISC3_PRN char(1) ,
	MISC4_PRN char(1) ,
	MISC5_PRN char(1) ,
	MISC6_PRN char(1) ,
	MISC1_TTL char(1) ,
	MISC2_TTL char(1) ,
	MISC3_TTL char(1) ,
	MISC4_TTL char(1) ,
	MISC5_TTL char(1) ,
	MISC6_TTL char(1) ,
	LABOR_MISC1_TTL char(1) ,
	LABOR_MISC2_TTL char(1) ,
	LABOR_MISC3_TTL char(1) ,
	LABOR_MISC4_TTL char(1) ,
	LABOR_MISC5_TTL char(1) ,
	LABOR_MISC6_TTL char(1) ,
	SUBT_TAX_A char(1) ,
	SUBT_TAX_B char(1) ,
	SUBT_TAX_C char(1) ,
	M1_TAX_A char(1) ,
	M1_TAX_B char(1) ,
	M1_TAX_C char(1) ,
	M2_TAX_A char(1) ,
	M2_TAX_B char(1) ,
	M2_TAX_C char(1) ,
	M3_TAX_A char(1) ,
	M3_TAX_B char(1) ,
	M3_TAX_C char(1) ,
	M4_TAX_A char(1) ,
	M4_TAX_B char(1) ,
	M4_TAX_C char(1) ,
	M5_TAX_A char(1) ,
	M5_TAX_B char(1) ,
	M5_TAX_C char(1) ,
	M6_TAX_A char(1) ,
	M6_TAX_B char(1) ,
	M6_TAX_C char(1) ,
	TAX_A_CODE char(5) NULL,
	TAX_B_CODE char(5) NULL,
	TAX_C_CODE char(5) NULL,
	TAX_A_GL char(15) NULL,
	TAX_B_GL char(15) NULL,
	TAX_C_GL char(15) NULL,
	TAX_A_TTL char(1) ,
	TAX_B_TTL char(1) ,
	TAX_C_TTL char(1) ,
	TAX_ON_TAX_B char(1) ,
	EXCH_CORE_CHRG char(1) ,
	EXCH_CORE_RETURN smallint ,
	EXCH_CORE_NOTE char(1) ,
	EXCH_CHARGE_FROM char(1) NULL,
	EXCH_CHARGE_COST char(1) NULL,
	EXCH_CORE_COST char(1) NULL,
	EXCH_CORE_PERC smallint ,
	CV_ALERT char(1) ,
	NO_AUTO_IMG_PRINT char(1) ,
	DEFAULT_CONTACT char(1) ,
	INV_ENTRY_NOT_APPROVED char(1) ,
	AUTO_SPEC2000_CREATION char(1) ,
	EDI_SPEC_2000_ACTIVE char(1) ,
	EDI_WEB_SITE varchar(100) NULL,
	EDI_ACCOUNT varchar(30) NULL,
	EDI_PASSWORD varchar(20) NULL,
	EDI_USER_RESP_FILE varchar(255) NULL,
	EDI_USER_TRANS_FILE varchar(255) NULL,
	CV_TAX_ENTITY char(1) ,
	VAT_EXEMPTION char(1) ,
	PROCESS_AUTOMATICALLY char(1) ,
	CHECK_LIMIT_PRICE char(1) ,
	LIMIT_PRICE decimal(28, 9) ,
	SITA char(1) ,
	SITA_USER char(5) NULL,
	AUTOMATIC_SHIPPING char(1) ,
	SITA_AIRLINE varchar(5) NULL,
	SITA_CITY varchar(5) NULL,
	SITA_DEPARTMENT varchar(5) NULL,
	AEROXCHANGE char(1) ,
	AUTOMATED_QUOTE_TO_RFQ char(1) ,
	END_USER_STATEMENT_REQUIRED char(1) ,
	END_USER_STATEMENT_LAST_USER char(5) NULL,
	END_USER_STATEMENT_REVIEW_DATE datetime NULL,
	DO_NOT_RECEIVE_MSG_VIA_EMAIL char(1) ,
	RECEIVE_RFQ_PO_AS_SMS char(1) ,
	E_MAX_OPEN_PO int NULL,
	E_MAX_PO_TOTAL_AMOUNT int ,
	MIN_GROSS_PROFIT decimal(28, 9) ,
	FLOOR_COST_PERCENT decimal(28, 9) ,
	MARKUP_PERC decimal(28, 9) ,
	RECLOCK char(4) NULL,
	ADDED_USR char(4) NULL,
	ADDED_DTE datetime NULL,
	UPDATED_USR char(4) NULL,
	UPDATED_DTE datetime NULL,
CONSTRAINT CUSTVENDSETUP_PK PRIMARY KEY (ACCTNO,SUBC,CUSTVEND)
);
